<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <PackageId>TTraxx.PluGui.NPlug</PackageId>
    <Description>Helper contract for NPlug implementations of the TTraxx.PluGui GUI library.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>PluGui_250x250.png</PackageIcon>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../assets/PluGui_250x250.png" Pack="true" PackagePath="\" />
    <None Include="../../README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NPlug" Version="0.5.0.380" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TTraxx.PluGui.Gui\TTraxx.PluGui.Gui.csproj" />
  </ItemGroup>

</Project>
