<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NPlug" Version="0.5.0.380" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TTraxx.PluGui.NPlug\TTraxx.PluGui.NPlug.csproj" />
  </ItemGroup>

</Project>
