<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <PackageId>TTraxx.PluGui.Harness.NPlug.Runners.Win32</PackageId>
    <Description>Test harness for NPlug implementations of the TTraxx.PluGui GUI library for the Windows platform.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>PluGui_250x250.png</PackageIcon>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../assets/PluGui_250x250.png" Pack="true" PackagePath="\" />
    <None Include="../../README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TTraxx.PluGui.Gui\TTraxx.PluGui.Gui.csproj" />
    <ProjectReference Include="..\TTraxx.PluGui.Harness.NPlug.Core\TTraxx.PluGui.Harness.NPlug.Core.csproj" />
  </ItemGroup>

</Project>
